// src/ai/flows/personalized-insights.ts
'use server';
/**
 * @fileOverview A flow for generating personalized insights after a declutter session.
 *
 * - generatePersonalizedInsights - A function that generates personalized insights based on the thoughts and feelings cleared during a session.
 * - PersonalizedInsightsInput - The input type for the generatePersonalizedInsights function.
 * - PersonalizedInsightsOutput - The return type for the generatePersonalizedInsights function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PersonalizedInsightsInputSchema = z.object({
  clearedThoughts: z.string().describe('A detailed summary of the thoughts, feelings, and ideas cleared during the declutter session.'),
  mood: z.string().describe('The mood selected by the user before the declutter session.'),
});
export type PersonalizedInsightsInput = z.infer<typeof PersonalizedInsightsInputSchema>;

const PersonalizedInsightsOutputSchema = z.object({
  insights: z.string().describe('Personalized insights generated by AI, tailored to the specific thoughts and feelings cleared during the session.'),
});
export type PersonalizedInsightsOutput = z.infer<typeof PersonalizedInsightsOutputSchema>;

export async function generatePersonalizedInsights(input: PersonalizedInsightsInput): Promise<PersonalizedInsightsOutput> {
  return personalizedInsightsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'personalizedInsightsPrompt',
  input: {schema: PersonalizedInsightsInputSchema},
  output: {schema: PersonalizedInsightsOutputSchema},
  prompt: `You are a mental wellness assistant providing personalized insights to users after their decluttering session.

  Based on the user's selected mood and the thoughts they cleared, provide insightful and actionable advice to help them understand their mental state and identify potential patterns or triggers.

  Be empathetic and supportive in your response.

  Selected Mood: {{{mood}}}
  Cleared Thoughts: {{{clearedThoughts}}}

  Personalized Insights:`,
});

const personalizedInsightsFlow = ai.defineFlow(
  {
    name: 'personalizedInsightsFlow',
    inputSchema: PersonalizedInsightsInputSchema,
    outputSchema: PersonalizedInsightsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return {insights: output!.insights};
  }
);
